name: freelunch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip>=23.0
  - numpy>=1.24.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - scipy>=1.10.0
  - jupyter>=1.0.0
  - ipykernel>=6.25.0
  - notebook>=7.0.0
  - scikit-learn>=1.3.0
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio
  - pytorch-cuda=12.1  # For CUDA support, adjust version as needed
  - pip:
    - yfinance>=0.2.28
    - pandas-datareader>=0.10.0
    - ta>=0.10.2
    - ta-lib>=0.4.28
    - beautifulsoup4>=4.12.0
    - lxml>=4.9.0
    - openpyxl>=3.1.0
    - xlrd>=2.0.1
    - plotly>=5.17.0
    - xgboost>=2.0.0
    - lightgbm>=4.0.0
    - optuna>=3.3.0
    - statsmodels>=0.14.0
    - arch>=6.2.0
    - ipywidgets>=8.1.0